package com.digitalchina.ftpclient.view;

import java.awt.event.ItemEvent;

import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import com.digitalchina.common.util.PropertiesUtil;
import com.digitalchina.ftpclient.model.Model;

/**
* 类描述：左边面板，用于显示本地文件列表
* 创建人：luo
* 创建时间：2014-7-8
* @version    
*/
 
public class LeftPanel extends javax.swing.JPanel {

	private Model model;

	/** Creates new form LeftPanel */
	public LeftPanel(Model model) {
		this.model = model;
		initComponents(); //初始化组件          
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		localLabel = new javax.swing.JLabel();
		jToolBar1 = new javax.swing.JToolBar();
		refreshLocalButton = new javax.swing.JButton();
		
		localPathText = new javax.swing.JTextField();
		localUpperButton = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		localFileList = new javax.swing.JList();

		setBackground(new java.awt.Color(204, 204, 204));

		localLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		localLabel.setText("\u672c\u5730");

		jToolBar1.setRollover(true);
		jToolBar1.setEnabled(false);

		refreshLocalButton.setText("\u5237\u65b0");
		refreshLocalButton.setFocusable(false);
		refreshLocalButton
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		refreshLocalButton
				.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		refreshLocalButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						refreshLocalButtonActionPerformed(evt);
					}
				});
		jToolBar1.add(refreshLocalButton);

		//String item[]=PropertiesUtil.getdataTypeList(model.getOrgInitial());
		
		/*jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"全部", "再生资源回收企业信息", "商贸行业协会、学会、社会中介信息", "服务外包企业信息", "外商企业信息",
				"外商投资企业变更信息", "新设境外投资企业信息" }));*/
		//if(null==item)
		//	item=new String[]{"全部"};

		localPathText.setText("...");
		localPathText.setFocusable(false);

		localUpperButton.setText("\u5411\u4e0a");

		localFileList.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4",
					"Item 5" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane1.setViewportView(localFileList);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(localLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
						450, Short.MAX_VALUE)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(10, 10, 10)
								.addComponent(jToolBar1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										428, Short.MAX_VALUE).addContainerGap())
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(localPathText,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										362, Short.MAX_VALUE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(localUpperButton)
								.addContainerGap())
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										426, Short.MAX_VALUE).addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(localLabel,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										20,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jToolBar1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										25,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														localPathText,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(localUpperButton))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										204, Short.MAX_VALUE).addContainerGap()));
	}// </editor-fold>

	private void refreshLocalButtonActionPerformed(
			java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshLocalButtonActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_refreshLocalButtonActionPerformed
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JToolBar.Separator jSeparator1;
	private javax.swing.JToolBar jToolBar1;
	private javax.swing.JList localFileList;
	private javax.swing.JLabel localLabel;
	private javax.swing.JTextField localPathText;
	private javax.swing.JButton localUpperButton;
	private javax.swing.JButton refreshLocalButton;

	// End of variables declaration//GEN-END:variables

	public JList getLocalFileList() {
		return localFileList;
	}

	public JTextField getLocalPathText() {
		return localPathText;
	}

	public JButton getLocalUpperButton() {
		return localUpperButton;
	}

	public JButton getRefreshLocalButton() {
		return refreshLocalButton;
	}

}
