/*
 * loginFtp.java
 *
 * Created on __DATE__, __TIME__
 */

package com.digitalchina.ftpclient.view;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
* 类描述：FTP登录界面
* 创建人：luo
* 创建时间：2014-7-8
* @version    
*/
public class loginFtp extends javax.swing.JDialog {

	/** Creates new form loginFtp */
	public loginFtp(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	public loginFtp() {
		initComponents(); // 初始化组件
		setVisible(false);// 默认状态不显示
	}
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jPasswordField1 = new javax.swing.JPasswordField();
		jButton1 = new javax.swing.JButton();

		//setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		
		//setVisible(false);
		setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
		setResizable(false);
		setLocationRelativeTo(null);
		setTitle("\u8fde\u63a5FTP");

		jLabel3.setText("\u7528\u6237\u540d\uff1a");

		jLabel4.setText("\u5bc6  \u7801\uff1a");

		jButton1.setText("\u8fde\u63a5");
		/*jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});*/

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(Alignment.LEADING, layout.createSequentialGroup()
					.addGap(66)
					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel3)
								.addComponent(jLabel4))
							.addGap(5)
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jTextField3, GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
								.addComponent(jPasswordField1, GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
							.addGap(14))
						.addGroup(layout.createSequentialGroup()
							.addPreferredGap(ComponentPlacement.RELATED, 114, GroupLayout.PREFERRED_SIZE)
							.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)))
					.addGap(107))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(48)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel3)
						.addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGap(18)
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jPasswordField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel4))
					.addGap(29)
					.addComponent(jButton1)
					.addContainerGap(52, Short.MAX_VALUE))
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/*private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}
*/
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				loginFtp dialog = new loginFtp(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
		//loginFtp dialog = new loginFtp();
		//dialog.setVisible(true);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	public javax.swing.JPasswordField getjPasswordField1() {
		return jPasswordField1;
	}

	public void setjPasswordField1(javax.swing.JPasswordField jPasswordField1) {
		this.jPasswordField1 = jPasswordField1;
	}

	

	public javax.swing.JTextField getjTextField3() {
		return jTextField3;
	}

	public void setjTextField3(javax.swing.JTextField jTextField3) {
		this.jTextField3 = jTextField3;
	}

	public javax.swing.JButton getjButton1() {
		return jButton1;
	}
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JTextField jTextField3;
	// End of variables declaration//GEN-END:variables

}