package com.digitalchina.ftpclient.view;

import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JTextField;
/**
* 类描述：右边面板，用于显示 ftp 服务器文件列表
* 创建人：luo
* 创建时间：2014-7-8
* @version    
*/
 
public class RightPanel extends javax.swing.JPanel {

	/** Creates new form RightPanel */
	public RightPanel() {
		initComponents();
		initData();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel2 = new javax.swing.JLabel();
		jToolBar2 = new javax.swing.JToolBar();
		remoteConnectButton = new javax.swing.JButton();
		jSeparator1 = new javax.swing.JToolBar.Separator();
		remoteDisconnectButton = new javax.swing.JButton();
		jSeparator3 = new javax.swing.JToolBar.Separator();
		refreshRemoteButton = new javax.swing.JButton();
		jSeparator2 = new javax.swing.JToolBar.Separator();
		deleteRemoteButton = new javax.swing.JButton();
		jSeparator4 = new javax.swing.JToolBar.Separator();
		remotePathText = new javax.swing.JTextField();
		remoteUpperButton = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		remoteFileList = new javax.swing.JList();

		setBackground(new java.awt.Color(204, 204, 204));

		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel2.setText("FTP \u670d\u52a1\u5668");

		jToolBar2.setRollover(true);
		jToolBar2.setEnabled(false);

		remoteConnectButton.setText("\u8fde\u63a5");
		remoteConnectButton.setFocusable(false);
		remoteConnectButton
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		remoteConnectButton
				.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		remoteConnectButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						remoteConnectButtonActionPerformed(evt);
					}
				});
		jToolBar2.add(remoteConnectButton);
		jToolBar2.add(jSeparator1);

		remoteDisconnectButton.setText("\u65ad\u5f00");
		remoteDisconnectButton.setFocusable(false);
		remoteDisconnectButton
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		remoteDisconnectButton
				.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jToolBar2.add(remoteDisconnectButton);
		jToolBar2.add(jSeparator3);

		refreshRemoteButton.setText("\u5237\u65b0");
		refreshRemoteButton.setFocusable(false);
		refreshRemoteButton
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		refreshRemoteButton
				.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jToolBar2.add(refreshRemoteButton);
		jToolBar2.add(jSeparator2);

		deleteRemoteButton.setText("\u5220\u9664");
		deleteRemoteButton.setFocusable(false);
		deleteRemoteButton
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		deleteRemoteButton
				.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jToolBar2.add(deleteRemoteButton);
		jToolBar2.add(jSeparator4);

		remotePathText.setEditable(false);
		remotePathText.setText("/");

		remoteUpperButton.setText("\u5411\u4e0a");

		remoteFileList.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4",
					"Item 5" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane1.setViewportView(remoteFileList);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
						405, Short.MAX_VALUE)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(10, 10, 10)
								.addComponent(jToolBar2,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										383, Short.MAX_VALUE).addContainerGap())
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(remotePathText,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										317, Short.MAX_VALUE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(remoteUpperButton)
								.addContainerGap())
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										381, Short.MAX_VALUE).addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jLabel2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										20,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jToolBar2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										25,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(remoteUpperButton)
												.addComponent(
														remotePathText,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										204, Short.MAX_VALUE).addContainerGap()));
	}// </editor-fold>
	//GEN-END:initComponents

	private void remoteConnectButtonActionPerformed(
			java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remoteConnectButtonActionPerformed
	// TODO add your handling code here:
	}//GEN-LAST:event_remoteConnectButtonActionPerformed

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton deleteRemoteButton;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JToolBar.Separator jSeparator1;
	private javax.swing.JToolBar.Separator jSeparator2;
	private javax.swing.JToolBar.Separator jSeparator3;
	private javax.swing.JToolBar.Separator jSeparator4;
	private javax.swing.JToolBar jToolBar2;
	private javax.swing.JButton refreshRemoteButton;
	private javax.swing.JButton remoteConnectButton;
	private javax.swing.JButton remoteDisconnectButton;
	private javax.swing.JList remoteFileList;
	private javax.swing.JTextField remotePathText;
	private javax.swing.JButton remoteUpperButton;

	// End of variables declaration//GEN-END:variables

	private void initData() {

	}

	//getter 方法
	public JButton getRefreshRemoteButton() {
		return refreshRemoteButton;
	}

	public JButton getRemoteConnectButton() {
		return remoteConnectButton;
	}

	public JList getRemoteFileList() {
		return remoteFileList;
	}

	public JTextField getRemotePathText() {
		return remotePathText;
	}

	public JButton getRemoteUpperButton() {
		return remoteUpperButton;
	}

	public JButton getRemoteDisconnectButton() {
		return remoteDisconnectButton;
	}

	public JButton getDeleteRemoteButton() {
		return deleteRemoteButton;
	}

}
